// <auto-generated />
using System;
using LoraStatsNet.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoraStatsNet.Database.Migrations
{
    [DbContext(typeof(LoraStatsNetDb))]
    partial class LoraStatsNetDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");
#pragma warning restore 612, 618
        }
    }
}
